### ISSUE TITLE
issue with hh_data and new fill_socio function 

### ISSUE THREAD

**Issue by mverma29** [samclifford/MeganVermaMsc#15] opened 2022-07-29 11:45 UTC
https://github.com/samclifford/MeganVermaMsc/blob/60a0a1aa7a64759fc4217334bee7f92d146a73f6/mscprojectscript_02_load_data.R#L199

"Error in `dplyr::summarise()`:
! Problem while computing `..1 = complete(data = dplyr::cur_data(), ..., fill = fill, explicit =
  explicit)`.
ℹ The error occurred in group 1: Country or area = "Afghanistan".
Caused by error in `grid_dots()`:
! `..2` must be a vector, not a function. "

I'm not sure what's wrong here, I don't see where we have used grid_dots()

**Comment by samclifford** [comment] 2022-07-29 11:49
It'll be the internals of a call to a dplyr/tidyr function

**Comment by mverma29** [comment] 2022-07-29 11:51
how would I go about fixing that? tidyverse is loaded last so it should be preferred, right

**Comment by samclifford** [comment] 2022-07-29 11:55
The issue isn't the order in which things are loaded, it's that something is being passed in that doesn't fit into what `fill_socio()` does.

**Comment by mverma29** [comment] 2022-07-29 11:58
ugh sorry, so dumb. accidentally dropped `year` and didnt notice

**Comment by samclifford** [comment] 2022-07-29 11:59
That's okay. I'm having a look now anyway.

**Comment by samclifford** [comment] 2022-07-29 12:23
Fixed in e4591dcd3c43b5ed5f662755e1239045024d91c7

**Comment by samclifford** [comment] 2022-07-29 12:23
Am currently looking at a few unexpectedly missing values in the hh data

**Comment by mverma29** [comment] 2022-07-29 12:54
yeah i would assume the scandi countries would have that data, weird

**Comment by samclifford** [comment] 2022-07-29 15:49
Sweden https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__BE__BE0101__BE0101S/HushallT05/table/tableViewLayout1/

Denmark https://www.statbank.dk/statbank5a/selectvarval/define.asp?PLanguage=1&subword=tabsel&MainTable=FAM55N&PXSId=206356&tablestyle=&ST=SD&buttons=0 

Iceland https://www.ceicdata.com/en/iceland/number-of-households/number-of-surveyed-household-members-average

Taiwan https://www.statista.com/statistics/922611/taiwan-average-number-of-people-per-household/#:~:text=In%202020%2C%20the%20average%20size,than%20in%20the%20previous%20year. 

Sri Lanka https://www.ceicdata.com/en/sri-lanka/household-income-and-expenditure-survey-household-size-and-number-of-income-receivers/hies-household-size#:~:text=Sri%20Lanka%20HIES%3A%20Household%20Size%20data%20was%20reported%20at%203.700,to%202019%2C%20with%2011%20observations.

Saudi Arabia https://doi.org/10.1177/2158244020914556

Still looking for New Caledonia and others

**Comment by samclifford** [comment] 2022-07-31 10:20
China's statistical yearbook might hold the answer for China. https://en.wikipedia.org/wiki/List_of_countries_by_number_of_households We will just need to check we have the right years avaiable

I am still looking for a New Caledonia source. Apparently there was a census in 2004 but I can only find metadata

**Comment by samclifford** [comment] 2022-08-01 10:13
> Sweden https://www.statistikdatabasen.scb.se/pxweb/en/ssd/START__BE__BE0101__BE0101S/HushallT05/table/tableViewLayout1/
> 
> Denmark https://www.statbank.dk/statbank5a/selectvarval/define.asp?PLanguage=1&subword=tabsel&MainTable=FAM55N&PXSId=206356&tablestyle=&ST=SD&buttons=0
> 
> Iceland https://www.ceicdata.com/en/iceland/number-of-households/number-of-surveyed-household-members-average
> 
> Taiwan https://www.statista.com/statistics/922611/taiwan-average-number-of-people-per-household/#:~:text=In%202020%2C%20the%20average%20size,than%20in%20the%20previous%20year.
> 
> Sri Lanka https://www.ceicdata.com/en/sri-lanka/household-income-and-expenditure-survey-household-size-and-number-of-income-receivers/hies-household-size#:~:text=Sri%20Lanka%20HIES%3A%20Household%20Size%20data%20was%20reported%20at%203.700,to%202019%2C%20with%2011%20observations.
> 
> Saudi Arabia https://doi.org/10.1177/2158244020914556
> 
> Still looking for New Caledonia and others

This has been added in daf8c9d559146f459717bb433eaa786f76c4a7f6

**Comment by samclifford** [comment] 2022-08-01 13:00
Added in 16ac01ac8b0392e51583e147dd49080c1500db46

China: http://www.stats.gov.cn/tjsj/ndsj/2021/indexeh.htm table 2-7

New Caledonia
1989 World Development Indicators 2008 ISBN 9780821373873
1990 Statistical Handbook on the World's Children (2002) ISBN 9781573563901
2004 UN POPULATION DIVISION file and taking weighted average
2014 https://pacificsecurity.net/wp-content/uploads/2021/02/Pacific_Islands_2020_Populations_poster.pdf
2021 https://www.prb.org/international/indicator/hh-size-av/table/

**Closed as completed by samclifford** 2022-08-01 13:00 UTC
